### ISSUE TITLE
development for feature 1

### ISSUE THREAD

**Issue by ossdhaval** [ossdhaval/gitcheck#14]
-------------------

### Description

- Original targeted issue
#13 

- Implementation Details
My implementation approach

-------------------

### Prepare

- [x] Read contribution guidelines
- [x] Read license information

-------------------

### Task breakdown

- [ ] dev task 1
- [ ] dev task 2
- [ ] dev task 3

-------------------

### Test cases and code coverage `NA`

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

-------------------

### Document the changes

- [ ] update samples in user guide
- [ ] task for updating installation and configuration guides if needed `NA`
- [ ] task for updating developer documentation if needed `NA`
- [ ] task for updating technical documentation if needed `NA`

**Comment by ossdhaval** [comment]
- [] new task
