### ISSUE TITLE
update samples in user guide

### ISSUE THREAD

**Issue by ossdhaval** [ossdhaval/gitcheck#18]

**Comment by ossdhaval** [comment]
[] check point 1

**Comment by ossdhaval** [comment]
-------------------

### Description

- Original targeted issue
#13 

- Implementation Details
My implementation approach


-------------------

### Prepare

- [x] Read contribution guidelines
- [x] Read license information

-------------------

### Task breakdown



- [ ] #15
- [ ] #16
- [ ] #17

-------------------

### Test cases and code coverage `NA`

- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

-------------------

### Document the changes



- [ ] #18
- [ ] task for updating installation and configuration guides if needed `NA`
- [ ] task for updating developer documentation if needed `NA`
- [ ] task for updating technical documentation if needed `NA`
